#include <string.h>

#include "../uart_wifi_scan_v1/floating_point_unit.h"
#include "../uart_wifi_scan_v1/phase_lock_loop.h"
#include "../uart_wifi_scan_v1/switches_and_leds.h"
#include "../uart_wifi_scan_v1/systick.h"
#include "../uart_wifi_scan_v1/uart_driver.h"
#include "../uart_wifi_scan_v1/wifi_scan.h"

int main();

/**
 *  Implements the first function that is called after initilizing the PC counter.
 *  See startup_TM4C123.s (file generated by Keil IDE) for more details.
 */
void SystemInit() {
	main();
}

/**
 * Initializes the different modules that are required to transmit the
 * Wifi Scan using the UART interface.
 *
 * - Phase Lock Loop (PLL) - Configure the clock at 50Mhz
 * - Systick - Enable a counter
 * - UART - Enable the UART 0
 * - GPIO - Enable Port F to support Switches and Leds
 *
 * Note: In order to save energy, the leds will be disabled in a production environment.
 *
 * When the user pressed the Switch 1, the Wifi Scan will be sent using the UART interface.
 * The RGB leds are using as a indicators.
 */
int main() {
	/**
	 * Defines the Wifi Scan data to be sent using the UART interface.
	 */
	const size_t kAccessPointCount = 2;
	const char *ssid_list[kAccessPointCount] = { "Nice", "Job" };
	const uint8_t bssid1[6] = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06 };
	const uint8_t bssid2[6] = { 0x11, 0x22, 0x33, 0x44, 0x55, 0x66 };
	const uint8_t *bssid_list[kAccessPointCount] = { bssid1, bssid2 };
	const float rssi_list[kAccessPointCount] = { -48.0f, -55.5f };

	initPhaseLockLoop();
	initSystick();
	initUart();
	initSwitchesAndLeds();
	initFloatingPointUnit();

	volatile unsigned long delay = 1;
	while (1) {
		if (isSwitch1Pressed()) {
			toggleLeds(GREEN);
			delay = 50; // 500 ms second
			sendWifiScanResult(kAccessPointCount, ssid_list, bssid_list,
					rssi_list);
		} else {
			turnOnLeds(SKY_BLUE);
			delay = 1;
		}

		// It is necessary to wait a few micro seconds to avoid the bouncing.
		wait10ms(delay);
	}
}

